'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5477
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AvengersGame.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property img_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_ancestral() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_ancestral", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_antman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_antman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_avengersgamelogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_avengersgamelogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_blackpanther() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_blackpanther", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_bucky() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_bucky", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_bw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_bw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_capi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_capi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_carol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_carol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_dr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_dr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_drax() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_drax", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_ego() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_ego", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_falcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_falcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_gamora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_gamora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_groot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_groot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_hawkeye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_hawkeye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_hela() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_hela", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_howard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_howard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_hulk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_hulk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_ironman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_ironman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_loki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_loki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_mantis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_mantis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_nebula() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_nebula", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_odin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_odin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_okoye() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_okoye", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_rayo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_rayo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_redskull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_redskull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_rescue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_rescue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_rocket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_rocket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_software() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_software", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_spiderman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_spiderman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_stanlee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_stanlee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_starlord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_starlord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_surtur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_surtur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_sw() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_sw", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_thanos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_thanos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_thor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_thor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_ultron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_ultron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_valkyrie() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_valkyrie", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_vision() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_vision", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_war() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_war", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_wasp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_wasp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property img_yondu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img_yondu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property snd_jugar() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_jugar", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property snd_lose() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_lose", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property snd_new() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_new", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property snd_selectdeck() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_selectdeck", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property snd_win() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("snd_win", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
